---
# TODO: add check monitoring_server_storage_dir exist

- name: Fail if using default_passwors
  ansible.builtin.fail:
    msg: "Error, change monitoring_server_grafana_security_admin_password"
  when: monitoring_server_grafana_enabled and monitoring_server_grafana_security_admin_password == monitoring_server_default_password
  # ignore_errors: True
