---
galaxy_info:
  author: Ivan Vinogradov <vinogradovia@gmail.com>
  description: configure monitoring stack
  license: WTFPL
  min_ansible_version: "2.2"
  galaxy_tags:
    - monitoring
dependencies: []
