---
# handlers file for monitoring-agent

- name: Restart Docker daemon
  ansible.builtin.service:
    name: docker
    state: restarted

- name: Reload systemd daemon
  ansible.builtin.systemd:
    daemon_reload: true

- name: State service node-exporter.socket
  ansible.builtin.systemd:
    name: "{{ monitoring_agent_node_exporter_systemd_name }}.socket"
    enabled: "{{ monitoring_agent_node_exporter_enabled }}"

- name: Restart service node-exporter
  ansible.builtin.systemd:
    name: "{{ monitoring_agent_node_exporter_systemd_name }}"
    enabled: "{{ monitoring_agent_node_exporter_enabled }}"
    state: restarted
